### PR TITLE
feature/language-selector add ability to manually switch language to frontend

### PR DESCRIPTION
**Pull request by ddamico**
## Description
In this PR we are adding a means to manually select the language for the frontend by:
* adding a new language selector component as a drop-down menu
* adding translation strings to support the menu
* adding a "supported languages" enum that the frontend uses as the actual source of truth for what languages are available (context: because loading translations via i18n-http-backend doesn't allow the frontend to have inherent awareness of what translations are available, for now we include a separate means to make this information available)

## Motivation and Context
This work was already near to completion in the old frontend repo, and thanks to @nielsmaerten contributing the remaining Dutch strings, we now have two translations for the frontend, so let's make them available and get this work completed.

## How Has This Been Tested?
Manually tested, unit tested.

## Additional context
Screen Shot 2021-05-01 at 3 44 39 PM
Above, at greater-than-mobile width, the selector is displayed with a label, while on mobile it collapses to just the icon and chevron...
Screen Shot 2021-05-01 at 3 44 12 PM
Screen Shot 2021-05-01 at 3 44 18 PM

## Types of changes
* New feature (non-breaking change which adds functionality)

## Checklist:

- [x] I've made my changes in a separate branch
- [ ] I've updated documentation, or created an issue to do so later
- [x] My change is passing new and existing tests

### CODE REVIEW

**Comment by ddamico** [comment]
@nielsmaerten Am I right to think that what I've done here with the new keys in the translations files is no longer how we do this?

**Comment by nielsmaerten** [comment]
> @nielsmaerten Am I right to think that what I've done here with the new keys in the translations files is no longer how we do this?

The current approach will probably be fine. Ideally, we would move all strings into the `common` package, and `frontend` would depend on it. But I think then we need some kind of pre-build step to extract the json files and place them in the /assets folder, no?

The biggest advantage of moving all strings into 1 package would be preventing duplicate strings. But since CrowdIn already handles duplicates very well, I'd consider it a nice-to-have

**Review by nielsmaerten — CHANGES_REQUESTED** [review]
Looks like the selected language is lost between page changes.  
To reproduce:

0. You're signed out
1. Open the root page (/)
2. Set language to Dutch
3. Sign in, get redirected to Google, then back to the root page
4. When the page reappears, the language is back to English. It should still be Dutch

Other example:

0. On the root page (/), and signed in
1. Set language to Dutch
2. Click "Verbinden met Nightscout" (Link your Nightscout)
3. The settings page appears, but it's in English. It should still be Dutch

**Comment by ddamico** [comment]
> Looks like the selected language is lost between page changes.
> To reproduce:
> 
> 1. You're signed out
> 2. Open the root page (/)
> 3. Set language to Dutch
> 4. Sign in, get redirected to Google, then back to the root page
> 5. When the page reappears, the language is back to English. It should still be Dutch
> 
> Other example:
> 
> 1. On the root page (/), and signed in
> 2. Set language to Dutch
> 3. Click "Verbinden met Nightscout" (Link your Nightscout)
> 4. The settings page appears, but it's in English. It should still be Dutch

😂 yup got focused on the wip on the menu and forgot the most important part of the feature. Looking into adding cookie-based persistence now. Will re-request review once it's ready!

**Comment by nielsmaerten** [comment]
> 😂 yup got focused on the wip on the menu and forgot the most important part of the feature. Looking into adding cookie-based persistence now. Will re-request review once it's ready!

Oops, I just moved 'querystring' to the top of the detection array in i18n.ts. bc Google prefers some way of setting the language in the URL, so it can link to the proper language (for example from the Actions Directory)  
Hope that won't interfere 😄

**Comment by ddamico** [comment]
> > 😂 yup got focused on the wip on the menu and forgot the most important part of the feature. Looking into adding cookie-based persistence now. Will re-request review once it's ready!
> 
> Oops, I just moved 'querystring' to the top of the detection array in i18n.ts. bc Google prefers some way of setting the language in the URL, so it can link to the proper language (for example from the Actions Directory)
> Hope that won't interfere 😄

Ah! Okay, if query-based is preferred by google then let's do that, I'll update the selection handler to support this.

**Comment by nielsmaerten** [comment]
Here's a link to Google's recommendations for multi-lingual sites: https://developers.google.com/search/docs/advanced/crawling/managing-multi-regional-sites?hl=en&visit_id=637554994656937806-3704866960&rd=1#use-different-urls-for-different-language-versions

Quote from that page:
> Google recommends using different URLs for each language version of a page rather than using cookies or browser settings to adjust the content language on the page.

So using the url is preferred over cookie or navigator, and [more specifically](https://developers.google.com/search/docs/advanced/crawling/managing-multi-regional-sites?hl=en&visit_id=637554994656937806-3704866960&rd=1#using-locale-specific-urls) https://glucocheck.app/en/settings is preferred over https://glucocheck.app/settings?lng=en

**Comment by ddamico** [comment]
> So using the url is preferred over cookie or navigator, and [more](https://developers.google.com/search/docs/advanced/crawling/managing-multi-regional-sites?hl=en&visit_id=637554994656937806-3704866960&rd=1#using-locale-specific-urls) specifically https://glucocheck.app/en/settings is preferred over https://glucocheck.app/settings?lng=en

Had been assuming that using url-param locales was going to a challenge better left for later, as far as integrating react-router and i18next, but as far as I can tell the implementation in the most recent commit is working just as we want and turned out to be very straightforward to implement.

**Review by nielsmaerten — CHANGES_REQUESTED** [review]
When changing the language using the dropdown, that change should probably be reflected in the url. Because otherwise the language isn't persisted between navigations:

0. At root page (/). Signed in, default language english
1. Set language to Dutch
2. Expected: the url changes to /nl ; Instead: the url is still /
3. Click 'Verbinden met Nightscout'
4. Expected: the settings page appears in Dutch, and the url changes to /nl/settings
  Instead: the settings page appears in English, and the url changes to /settings

**Comment by nielsmaerten** [comment]
> Had been assuming that using url-param locales was going to a challenge better left for later, as far as integrating react-router and i18next, but as far as I can tell the implementation in the most recent commit is working just as we want and turned out to be very straightforward to implement.

If it turns out detecting the url from the path is too tricky, pulling it from the querystring is perfectly fine. But it looks like you've got i18next and react-router working together like a charm already 🥳

**Comment by nielsmaerten** [comment]
Found another minor issue: the label on the Sign in with Google button isn't updating when changing the language.

0. At root page, signed out. Default language english
1. Set language to Dutch
2. Expected: "Sign in with Google" changes to "Aanmelden met Google"
  Instead: The page language changes, except the Google sign in button. The text is still "Sign in with Google"

**Comment by nielsmaerten** [comment]
Maybe related to: https://github.com/nielsmaerten/gluco-check/pull/116#pullrequestreview-649823082 ?
https://github.com/nielsmaerten/gluco-check/blob/f6e4000a874699fee55642d8941539cb2e18ba88/gluco-check-frontend/src/pages/Welcome.tsx#L89  
It looks like this button is doing a full page refresh? It's navigation is not handled by React-Router, instead doing a GET request back to the server and reloading the whole page.

Sorry if I'm nitpicking btw 😅

**Comment by ddamico** [comment]
> Sorry if I'm nitpicking btw 😅

No not at all this is great, I was not paying close enough attention yesterday, and your feedback was very helpful. I think I've now got the url issues sorted out.

The not-updating sign-in button turns out to be more complicated...

The fullLabel in the ui config that's passed to `<StyledFirebaseAuth>` does not update after the initial render. Nothing I've tried has been able to get around that. The "proper" way to work around this would be, I think, to not set a label here at all and set the locale on `firebaseui` when the i18next `languageChanged` event fires, and let the library to do work. But this would require including localized versions of firebaseui, which run ~200kb each, which doesn't seem worth it for what we're trying to do here.

What seemed like the lowest-impact way to achieve this was... actually navigate with a window.location.assign when the user chooses a language. Not that much to reload, hopefully a user's not going to trigger this _that_ often, and has the overall desired effect. Let me know if you disagree, it's what I've currently got implemented.

**Comment by nielsmaerten** [comment]
> What seemed like the lowest-impact way to achieve this was... actually navigate with a window.location.assign when the user chooses a language. Not that much to reload, hopefully a user's not going to trigger this _that_ often, and has the overall desired effect. Let me know if you disagree, it's what I've currently got implemented.

This seems like a good approach 👍   
I agree it's not worth downloading a 200kb l10n package for an event that probably rare.  
And a full page refresh will still be relatively fast thanks to browser and CDN caching

**Comment by nielsmaerten** [comment]
Looks like the Metrics aren't getting translated yet:

image

**Comment by ddamico** [comment]
> Looks like the Metrics aren't getting translated yet:
> 
> image

😭 the code was already there, it just wasn't being used. What's the translation for "pump reservoir"?

**Comment by nielsmaerten** [comment]
> 😭 the code was already there, it just wasn't being used. What's the translation for "pump reservoir"?

"Pomp reservoir" 😁 99% the same.  
It's fine to have those translations duplicated in frontend and backend btw. CrowdIn will make sure they're only translated once.

**Review by nielsmaerten — APPROVED** [review]
# :shipit: 
Looking great! hipit:

**Pull request merged**
